In [6]:
import numpy as np
my_list=[1,2,3]
my_array=np.array([1,2,3])

print(type(my_list))


<class 'list'>


In [7]:
print(np.array(my_list))

[1 2 3]


In [8]:
my_matrix=[[1,2,3],[4,5,6],[7,8,9]]
print(np.array(my_matrix))

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [10]:
print(np.arange(0,10))
print(np.arange(0,11,2))

[0 1 2 3 4 5 6 7 8 9]
[ 0  2  4  6  8 10]


In [12]:
print(np.zeros(3))
print(np.ones(3))
print(np.zeros((5,5)))
print(np.ones((3,3)))

[0. 0. 0.]
[1. 1. 1.]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [13]:
print(np.linspace(0,10,3))
print(np.linspace(0,5,20))
print(np.linspace(0,5,21))

[ 0.  5. 10.]
[0.         0.26315789 0.52631579 0.78947368 1.05263158 1.31578947
 1.57894737 1.84210526 2.10526316 2.36842105 2.63157895 2.89473684
 3.15789474 3.42105263 3.68421053 3.94736842 4.21052632 4.47368421
 4.73684211 5.        ]
[0.   0.25 0.5  0.75 1.   1.25 1.5  1.75 2.   2.25 2.5  2.75 3.   3.25
 3.5  3.75 4.   4.25 4.5  4.75 5.  ]


In [14]:
print(np.random.rand(2))
print(np.random.rand(5,5))

[0.80136747 0.09084747]
[[0.3397022  0.45559586 0.56875939 0.37829912 0.54865555]
 [0.27145081 0.82458478 0.18472098 0.76421926 0.63086771]
 [0.29291049 0.13170984 0.84888136 0.80879197 0.55456528]
 [0.43755205 0.71009984 0.1869286  0.39908111 0.67217362]
 [0.6606248  0.81936124 0.31822496 0.57572342 0.3500361 ]]


In [15]:
print(np.random.randn(2))
print(np.random.randn(5,5))

[-1.67090969  0.46992463]
[[ 0.08653206 -0.84304943 -0.92056047 -1.03699721 -1.03620925]
 [-0.07812183  2.36391881  1.69284785 -0.54066593  1.01625217]
 [ 0.63794204  0.09794853  0.4810922  -1.28436547  1.6820818 ]
 [-0.11014851 -0.6519075  -0.0906341   0.72077764  2.06992642]
 [-0.52182391 -1.86335127 -1.2251846   0.35555986 -1.16698033]]


In [16]:
print(np.random.randint(1,100))
print(np.random.randint(1,100,10))

52
[ 6 78 82 23 26 74 72 86 98 29]


In [17]:
np.random.seed(42) 
print(np.random.rand(4))

[0.37454012 0.95071431 0.73199394 0.59865848]


In [21]:
arr=np.arange(25)
ranarr=np.random.randint(0,50,10)
print(arr)
print(ranarr)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]
[21 43 24 48 26 41 27 15 14 46]


In [22]:
print(arr.reshape(5,5))

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [29]:
print(max(ranarr))
print(min(ranarr))
print(arr.max())
print(ranarr.argmax())
print(arr.min())
print(arr.argmax())


48
14
24
3
0
24


In [41]:
arr=np.arange(0,11)
print(arr)
print(arr[8])
print(arr[1:5])
print(arr[0:5])

[ 0  1  2  3  4  5  6  7  8  9 10]
8
[1 2 3 4]
[0 1 2 3 4]


In [42]:
arr[0:5] = 100
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [43]:
slice = arr[0:5]
slice

array([100, 100, 100, 100, 100])

In [45]:
slice[:] = 900
slice

array([900, 900, 900, 900, 900])

In [46]:
print(arr)

[900 900 900 900 900   5   6   7   8   9  10]


In [47]:
arr_2d=np.array(([5,10,15],[20,3,34],[78,2,44]))
print(arr_2d)

[[ 5 10 15]
 [20  3 34]
 [78  2 44]]


In [48]:
print(arr_2d[1])

[20  3 34]


In [49]:
print(arr_2d[1][0])
print(arr_2d[1,0])
print(arr_2d[:2,1:])

20
20
[[10 15]
 [ 3 34]]


In [51]:
arr=np.arange(1,11)
print(arr)
print(arr>4)
bool_arr = arr>5
print(bool_arr)

[ 1  2  3  4  5  6  7  8  9 10]
[False False False False  True  True  True  True  True  True]
[False False False False False  True  True  True  True  True]


In [52]:
print(arr[bool_arr])

[ 6  7  8  9 10]


In [61]:
arr=np.arange(0,10)
print(arr+arr)
print(arr-arr)
print(arr*arr)

[ 0  2  4  6  8 10 12 14 16 18]
[0 0 0 0 0 0 0 0 0 0]
[ 0  1  4  9 16 25 36 49 64 81]


In [65]:
#print(arr/arr)
#print(1/arr)
print(arr**3)
print(np.sqrt(arr))
print(np.exp(arr))
print(np.sin(arr))
#print(np.log(arr))

[  0   1   8  27  64 125 216 343 512 729]
[0.         1.         1.41421356 1.73205081 2.         2.23606798
 2.44948974 2.64575131 2.82842712 3.        ]
[1.00000000e+00 2.71828183e+00 7.38905610e+00 2.00855369e+01
 5.45981500e+01 1.48413159e+02 4.03428793e+02 1.09663316e+03
 2.98095799e+03 8.10308393e+03]
[ 0.          0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427
 -0.2794155   0.6569866   0.98935825  0.41211849]


In [66]:
print(arr.sum())
print(arr.mean())
print(arr.max())
print(arr.min())
print(arr.var())
print(arr.std())

45
4.5
9
0
8.25
2.8722813232690143


In [69]:
arr_2d=np.array([[1,2,3,4],[44,55,66,77],[9,10,11,12]])
print(arr_2d)
print(arr_2d.sum(axis=0))
print(arr_2d.sum(axis=1))
print(arr_2d.shape)


[[ 1  2  3  4]
 [44 55 66 77]
 [ 9 10 11 12]]
[54 67 80 93]
[ 10 242  42]
(3, 4)


In [70]:
import numpy as np
import pandas as pd
myindex=['USA','CANADA','England']
mydata=[1776,1876,1821]
myser=pd.Series(data=mydata)
print(myser)

0    1776
1    1876
2    1821
dtype: int64


In [71]:
myser=pd.Series(data=mydata,index=myindex)
myser

USA        1776
CANADA     1876
England    1821
dtype: int64

In [75]:
ran_data = np.random.randint(0,100,4)
print(ran_data)

[72 38 17  3]


In [76]:
names=["Alice","Bob","Charles","Dave"]
ages=pd.Series(ran_data,names)
print(ages)

Alice      72
Bob        38
Charles    17
Dave        3
dtype: int32


In [77]:
ages={"Sammy":5,"Frank":10,"Spike":7}
print(ages)
print(pd.Series(ages))

{'Sammy': 5, 'Frank': 10, 'Spike': 7}
Sammy     5
Frank    10
Spike     7
dtype: int64


In [79]:
q1={"Japan":80,"China":450,"India":200,"USA":250}
q2={"Brazil":100,"China":550,"India":210,"USA":260}
sales_Q1=pd.Series(q1)
sales_Q2=pd.Series(q2)
print(sales_Q1)
print(sales_Q2)

Japan     80
China    450
India    200
USA      250
dtype: int64
Brazil    100
China     550
India     210
USA       260
dtype: int64


In [84]:
print(sales_Q1["Japan"])
#print(sales_Q1[0])
#print(sales_Q1["France"]) error
#print(sales_Q1["Japan "]) error

80


In [86]:
print(sales_Q1.keys())
print(sales_Q1/100)
print(sales_Q1*2)

Index(['Japan', 'China', 'India', 'USA'], dtype='object')
Japan    0.8
China    4.5
India    2.0
USA      2.5
dtype: float64
Japan    160
China    900
India    400
USA      500
dtype: int64


In [87]:
print(sales_Q1+sales_Q2)

Brazil       NaN
China     1000.0
India      410.0
Japan        NaN
USA        510.0
dtype: float64


In [88]:
print(sales_Q1.add(sales_Q2,fill_value=0))

Brazil     100.0
China     1000.0
India      410.0
Japan       80.0
USA        510.0
dtype: float64
