In [2]:
import pandas as pd
import numpy as np
np.random.seed(101)
my_data=np.random.randint(0,101,(4,3))
print(my_data)

[[95 11 81]
 [70 63 87]
 [75  9 77]
 [40  4 63]]


In [3]:
myindex=["CA","NY","AZ","TX"]
mycolumns=["Jan","Feb","Mar"]
df = pd.DataFrame(data=my_data)
print(df)

    0   1   2
0  95  11  81
1  70  63  87
2  75   9  77
3  40   4  63


In [4]:
df = pd.DataFrame(data=my_data,index=myindex)
print(df) 

     0   1   2
CA  95  11  81
NY  70  63  87
AZ  75   9  77
TX  40   4  63


In [5]:
df = pd.DataFrame(data=my_data,index=myindex,columns=mycolumns)
print(df)

    Jan  Feb  Mar
CA   95   11   81
NY   70   63   87
AZ   75    9   77
TX   40    4   63


In [18]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
Index: 243 entries, Sun4608 to Thur672
Data columns (total 10 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   total_bill        243 non-null    float64
 1   tip               243 non-null    float64
 2   gender            243 non-null    object 
 3   smoker            243 non-null    object 
 4   day               243 non-null    object 
 5   time              243 non-null    object 
 6   size              243 non-null    int64  
 7   price_per_person  243 non-null    float64
 8   Payer Name        243 non-null    object 
 9   CC Number         243 non-null    float64
dtypes: float64(4), int64(1), object(5)
memory usage: 29.0+ KB
None


In [19]:
df= pd.read_csv("tips.csv")
df

total_bill   tip  gender smoker   day    time  size  price_per_person  \
0         16.99  1.01  Female     No   Sun  Dinner     2              8.49   
1         10.34  1.66    Male     No   Sun  Dinner     3              3.45   
2         21.01  3.50    Male     No   Sun  Dinner     3              7.00   
3         23.68  3.31    Male     No   Sun  Dinner     2             11.84   
4         24.59  3.61  Female     No   Sun  Dinner     4              6.15   
..          ...   ...     ...    ...   ...     ...   ...               ...   
239       29.03  5.92    Male     No   Sat  Dinner     3              9.68   
240       27.18  2.00  Female    Yes   Sat  Dinner     2             13.59   
241       22.67  2.00    Male    Yes   Sat  Dinner     2             11.34   
242       17.82  1.75    Male     No   Sat  Dinner     2              8.91   
243       18.78  3.00  Female     No  Thur  Dinner     2              9.39   

             Payer Name     CC Number Payment ID  
0    Christy Cunningham  3.560330e+15    Sun2959  
1        Douglas Tucker  4.478070e+15    Sun4608  
2        Travis Walters  6.011810e+15    Sun4458  
3      Nathaniel Harris  4.676140e+15    Sun5260  
4          Tonya Carter  4.832730e+15    Sun2251  
..                  ...           ...        ...  
239       Michael Avila  5.296070e+15    Sat2657  
240      Monica Sanders  3.506810e+15    Sat1766  
241          Keith Wong  6.011890e+15    Sat3880  
242        Dennis Dixon  4.375220e+12      Sat17  
243     Michelle Hardin  3.511450e+15    Thur672  

[244 rows x 11 columns]

In [20]:
print(df.iloc[0])

total_bill                       16.99
tip                               1.01
gender                          Female
smoker                              No
day                                Sun
time                            Dinner
size                                 2
price_per_person                  8.49
Payer Name          Christy Cunningham
CC Number           3560330000000000.0
Payment ID                     Sun2959
Name: 0, dtype: object


In [21]:
df=df.set_index('Payment ID')
print(df.loc['Sun2959'])

total_bill                       16.99
tip                               1.01
gender                          Female
smoker                              No
day                                Sun
time                            Dinner
size                                 2
price_per_person                  8.49
Payer Name          Christy Cunningham
CC Number           3560330000000000.0
Name: Sun2959, dtype: object


In [22]:
print(df.head())

            total_bill   tip  gender smoker  day    time  size  \
Payment ID                                                       
Sun2959          16.99  1.01  Female     No  Sun  Dinner     2   
Sun4608          10.34  1.66    Male     No  Sun  Dinner     3   
Sun4458          21.01  3.50    Male     No  Sun  Dinner     3   
Sun5260          23.68  3.31    Male     No  Sun  Dinner     2   
Sun2251          24.59  3.61  Female     No  Sun  Dinner     4   

            price_per_person          Payer Name     CC Number  
Payment ID                                                      
Sun2959                 8.49  Christy Cunningham  3.560330e+15  
Sun4608                 3.45      Douglas Tucker  4.478070e+15  
Sun4458                 7.00      Travis Walters  6.011810e+15  
Sun5260                11.84    Nathaniel Harris  4.676140e+15  
Sun2251                 6.15        Tonya Carter  4.832730e+15  


In [23]:
df=df.drop('Sun2959',axis=0)
print(df.head())

            total_bill   tip  gender smoker  day    time  size  \
Payment ID                                                       
Sun4608          10.34  1.66    Male     No  Sun  Dinner     3   
Sun4458          21.01  3.50    Male     No  Sun  Dinner     3   
Sun5260          23.68  3.31    Male     No  Sun  Dinner     2   
Sun2251          24.59  3.61  Female     No  Sun  Dinner     4   
Sun9679          25.29  4.71    Male     No  Sun  Dinner     4   

            price_per_person        Payer Name     CC Number  
Payment ID                                                    
Sun4608                 3.45    Douglas Tucker  4.478070e+15  
Sun4458                 7.00    Travis Walters  6.011810e+15  
Sun5260                11.84  Nathaniel Harris  4.676140e+15  
Sun2251                 6.15      Tonya Carter  4.832730e+15  
Sun9679                 6.32        Erik Smith  2.131400e+14  


In [24]:
df['total_bill']>30

Payment ID
Sun4608    False
Sun4458    False
Sun5260    False
Sun2251    False
Sun9679    False
           ...  
Sat2657    False
Sat1766    False
Sat3880    False
Sat17      False
Thur672    False
Name: total_bill, Length: 243, dtype: bool

In [25]:
df['total_bill']<30

Payment ID
Sun4608    True
Sun4458    True
Sun5260    True
Sun2251    True
Sun9679    True
           ... 
Sat2657    True
Sat1766    True
Sat3880    True
Sat17      True
Thur672    True
Name: total_bill, Length: 243, dtype: bool

In [28]:
bool_series=df['total_bill']>30
print(bool_series)


Payment ID
Sun4608    False
Sun4458    False
Sun5260    False
Sun2251    False
Sun9679    False
           ...  
Sat2657    False
Sat1766    False
Sat3880    False
Sat17      False
Thur672    False
Name: total_bill, Length: 243, dtype: bool


In [29]:
print(df[bool_series])

            total_bill    tip  gender smoker   day    time  size  \
Payment ID                                                         
Sun6686          35.26   5.00  Female     No   Sun  Dinner     4   
Sat239           39.42   7.58    Male     No   Sat  Dinner     4   
Sat6373          31.27   5.00    Male     No   Sat  Dinner     3   
Sun2274          30.40   5.60    Male     No   Sun  Dinner     4   
Sun9677          32.40   6.00    Male     No   Sun  Dinner     4   
Sun6165          34.81   5.20  Female     No   Sun  Dinner     4   
Sat8903          38.01   3.00    Male    Yes   Sat  Dinner     4   
Sat8139          48.27   6.73    Male     No   Sat  Dinner     4   
Thur8801         32.68   5.00    Male    Yes  Thur   Lunch     2   
Thur7972         34.83   5.17  Female     No  Thur   Lunch     4   
Fri9628          40.17   4.73    Male    Yes   Fri  Dinner     4   
Sat6240          44.30   2.50  Female    Yes   Sat  Dinner     3   
Sun591           38.07   4.00    Male     No   S

In [32]:
print(df[df['total_bill']>30])
#print(df[df.total_bill>30)

            total_bill    tip  gender smoker   day    time  size  \
Payment ID                                                         
Sun6686          35.26   5.00  Female     No   Sun  Dinner     4   
Sat239           39.42   7.58    Male     No   Sat  Dinner     4   
Sat6373          31.27   5.00    Male     No   Sat  Dinner     3   
Sun2274          30.40   5.60    Male     No   Sun  Dinner     4   
Sun9677          32.40   6.00    Male     No   Sun  Dinner     4   
Sun6165          34.81   5.20  Female     No   Sun  Dinner     4   
Sat8903          38.01   3.00    Male    Yes   Sat  Dinner     4   
Sat8139          48.27   6.73    Male     No   Sat  Dinner     4   
Thur8801         32.68   5.00    Male    Yes  Thur   Lunch     2   
Thur7972         34.83   5.17  Female     No  Thur   Lunch     4   
Fri9628          40.17   4.73    Male    Yes   Fri  Dinner     4   
Sat6240          44.30   2.50  Female    Yes   Sat  Dinner     3   
Sun591           38.07   4.00    Male     No   S

In [33]:
print(df[df['gender']=='Male'])

            total_bill   tip gender smoker  day    time  size  \
Payment ID                                                      
Sun4608          10.34  1.66   Male     No  Sun  Dinner     3   
Sun4458          21.01  3.50   Male     No  Sun  Dinner     3   
Sun5260          23.68  3.31   Male     No  Sun  Dinner     2   
Sun9679          25.29  4.71   Male     No  Sun  Dinner     4   
Sun5985           8.77  2.00   Male     No  Sun  Dinner     2   
...                ...   ...    ...    ...  ...     ...   ...   
Sat5032          12.60  1.00   Male    Yes  Sat  Dinner     2   
Sat2929          32.83  1.17   Male    Yes  Sat  Dinner     2   
Sat2657          29.03  5.92   Male     No  Sat  Dinner     3   
Sat3880          22.67  2.00   Male    Yes  Sat  Dinner     2   
Sat17            17.82  1.75   Male     No  Sat  Dinner     2   

            price_per_person          Payer Name     CC Number  
Payment ID                                                      
Sun4608                 

In [36]:
df_new = df[(df['total_bill']>30)&(df['gender']=='Male')]
print(df_new)

            total_bill    tip gender smoker   day    time  size  \
Payment ID                                                        
Sat239           39.42   7.58   Male     No   Sat  Dinner     4   
Sat6373          31.27   5.00   Male     No   Sat  Dinner     3   
Sun2274          30.40   5.60   Male     No   Sun  Dinner     4   
Sun9677          32.40   6.00   Male     No   Sun  Dinner     4   
Sat8903          38.01   3.00   Male    Yes   Sat  Dinner     4   
Sat8139          48.27   6.73   Male     No   Sat  Dinner     4   
Thur8801         32.68   5.00   Male    Yes  Thur   Lunch     2   
Fri9628          40.17   4.73   Male    Yes   Fri  Dinner     4   
Sun591           38.07   4.00   Male     No   Sun  Dinner     3   
Thur1025         34.30   6.70   Male     No  Thur   Lunch     6   
Thur3621         41.19   5.00   Male     No  Thur   Lunch     5   
Sun7518          48.17   5.00   Male     No   Sun  Dinner     6   
Sun3719          31.71   4.50   Male     No   Sun  Dinner     

In [37]:
df_new = df[(df['total_bill']>30)&~(df['gender']=='Male')]
print(df_new)

            total_bill   tip  gender smoker   day    time  size  \
Payment ID                                                        
Sun6686          35.26  5.00  Female     No   Sun  Dinner     4   
Sun6165          34.81  5.20  Female     No   Sun  Dinner     4   
Thur7972         34.83  5.17  Female     No  Thur   Lunch     4   
Sat6240          44.30  2.50  Female    Yes   Sat  Dinner     3   
Thur9313         43.11  5.00  Female    Yes  Thur   Lunch     4   
Sat8863          30.14  3.09  Female    Yes   Sat  Dinner     4   
Sat9777          35.83  4.67  Female     No   Sat  Dinner     3   

            price_per_person      Payer Name     CC Number  
Payment ID                                                  
Sun6686                 8.82    Diane Macias  4.577820e+15  
Sun6165                 8.70    Emily Daniel  4.291280e+15  
Thur7972                8.71     Shawna Cook  6.011790e+15  
Sat6240                14.77   Heather Cohen  3.797710e+14  
Thur9313               10.78  

In [39]:
df_new = df[(df['total_bill']>30)&(df['gender']!='Male')]
print(df_new)

            total_bill   tip  gender smoker   day    time  size  \
Payment ID                                                        
Sun6686          35.26  5.00  Female     No   Sun  Dinner     4   
Sun6165          34.81  5.20  Female     No   Sun  Dinner     4   
Thur7972         34.83  5.17  Female     No  Thur   Lunch     4   
Sat6240          44.30  2.50  Female    Yes   Sat  Dinner     3   
Thur9313         43.11  5.00  Female    Yes  Thur   Lunch     4   
Sat8863          30.14  3.09  Female    Yes   Sat  Dinner     4   
Sat9777          35.83  4.67  Female     No   Sat  Dinner     3   

            price_per_person      Payer Name     CC Number  
Payment ID                                                  
Sun6686                 8.82    Diane Macias  4.577820e+15  
Sun6165                 8.70    Emily Daniel  4.291280e+15  
Thur7972                8.71     Shawna Cook  6.011790e+15  
Sat6240                14.77   Heather Cohen  3.797710e+14  
Thur9313               10.78  

In [45]:
df_new = df[(df['total_bill']>40)|(df['tip']>5)]
print(df_new)

            total_bill    tip  gender smoker   day    time  size  \
Payment ID                                                         
Sat239           39.42   7.58    Male     No   Sat  Dinner     4   
Sun2274          30.40   5.60    Male     No   Sun  Dinner     4   
Sun9677          32.40   6.00    Male     No   Sun  Dinner     4   
Sun6165          34.81   5.20  Female     No   Sun  Dinner     4   
Sat8139          48.27   6.73    Male     No   Sat  Dinner     4   
Thur7972         34.83   5.17  Female     No  Thur   Lunch     4   
Thur9003         24.71   5.85    Male     No  Thur   Lunch     2   
Fri9628          40.17   4.73    Male    Yes   Fri  Dinner     4   
Sat6240          44.30   2.50  Female    Yes   Sat  Dinner     3   
Sun22            29.93   5.07    Male     No   Sun  Dinner     4   
Thur1025         34.30   6.70    Male     No  Thur   Lunch     6   
Thur3621         41.19   5.00    Male     No  Thur   Lunch     5   
Sun9176          29.85   5.14  Female     No   S

In [47]:
options = ["Sat","Sun"]
print(df['day'].isin(options))

Payment ID
Sun4608     True
Sun4458     True
Sun5260     True
Sun2251     True
Sun9679     True
           ...  
Sat2657     True
Sat1766     True
Sat3880     True
Sat17       True
Thur672    False
Name: day, Length: 243, dtype: bool


In [48]:
print(df[df['day'].isin(["Sat","Sun"])])

            total_bill   tip  gender smoker  day    time  size  \
Payment ID                                                       
Sun4608          10.34  1.66    Male     No  Sun  Dinner     3   
Sun4458          21.01  3.50    Male     No  Sun  Dinner     3   
Sun5260          23.68  3.31    Male     No  Sun  Dinner     2   
Sun2251          24.59  3.61  Female     No  Sun  Dinner     4   
Sun9679          25.29  4.71    Male     No  Sun  Dinner     4   
...                ...   ...     ...    ...  ...     ...   ...   
Sat9777          35.83  4.67  Female     No  Sat  Dinner     3   
Sat2657          29.03  5.92    Male     No  Sat  Dinner     3   
Sat1766          27.18  2.00  Female    Yes  Sat  Dinner     2   
Sat3880          22.67  2.00    Male    Yes  Sat  Dinner     2   
Sat17            17.82  1.75    Male     No  Sat  Dinner     2   

            price_per_person        Payer Name     CC Number  
Payment ID                                                    
Sun4608        

In [50]:
print(df.sort_values("tip"))

            total_bill    tip  gender smoker   day    time  size  \
Payment ID                                                         
Sat5032          12.60   1.00    Male    Yes   Sat  Dinner     2   
Sat4801           7.25   1.00  Female     No   Sat  Dinner     1   
Fri3780           5.75   1.00  Female    Yes   Fri  Dinner     2   
Sat3455           3.07   1.00  Female    Yes   Sat  Dinner     1   
Sat6983          12.90   1.10  Female    Yes   Sat  Dinner     2   
...                ...    ...     ...    ...   ...     ...   ...   
Thur1025         34.30   6.70    Male     No  Thur   Lunch     6   
Sat8139          48.27   6.73    Male     No   Sat  Dinner     4   
Sat239           39.42   7.58    Male     No   Sat  Dinner     4   
Sat4590          48.33   9.00    Male     No   Sat  Dinner     4   
Sat1954          50.81  10.00    Male    Yes   Sat  Dinner     3   

            price_per_person       Payer Name     CC Number  
Payment ID                                           

In [52]:
print(df[["total_bill","tip"]].corr())

            total_bill       tip
total_bill    1.000000  0.676901
tip           0.676901  1.000000


In [53]:
print(df["smoker"].value_counts())
print(df["gender"].value_counts())

smoker
No     150
Yes     93
Name: count, dtype: int64
gender
Male      157
Female     86
Name: count, dtype: int64


In [54]:
print(df["size"].unique())
print(df["size"].nunique())
print(df["time"].unique())

[3 2 4 1 6 5]
6
['Dinner' 'Lunch']


In [55]:
print(df["total_bill"].between(10,20,inclusive="both"))

Payment ID
Sun4608     True
Sun4458    False
Sun5260    False
Sun2251    False
Sun9679    False
           ...  
Sat2657    False
Sat1766    False
Sat3880    False
Sat17       True
Thur672     True
Name: total_bill, Length: 243, dtype: bool


In [56]:
print(df[df["total_bill"].between(10,20,inclusive="both")])

            total_bill   tip  gender smoker   day    time  size  \
Payment ID                                                        
Sun4608          10.34  1.66    Male     No   Sun  Dinner     3   
Sun6820          15.04  1.96    Male     No   Sun  Dinner     2   
Sun3775          14.78  3.23    Male     No   Sun  Dinner     2   
Sun2546          10.27  1.71    Male     No   Sun  Dinner     2   
Sun1300          15.42  1.57    Male     No   Sun  Dinner     2   
...                ...   ...     ...    ...   ...     ...   ...   
Sat7220          15.53  3.00    Male    Yes   Sat  Dinner     2   
Sat4615          10.07  1.25    Male     No   Sat  Dinner     2   
Sat5032          12.60  1.00    Male    Yes   Sat  Dinner     2   
Sat17            17.82  1.75    Male     No   Sat  Dinner     2   
Thur672          18.78  3.00  Female     No  Thur  Dinner     2   

            price_per_person       Payer Name     CC Number  
Payment ID                                                   
Sun4